Update README.md
There was a bug where the call to `cp.GetRowsCount()` was incorrectly using an uppercase `G` rather than a lowercase `g`.  This causes the error below.  I fixed this to be `cp.getRowsCount()`.

```
C:\Users\zam26\Documents\Code\Arduino\Projects\SunriseSunset\SunriseSunset.ino: In function 'void setup()':
SunriseSunset:47:26: error: 'class CSV_Parser' has no member named 'GetRowsCount'; did you mean 'getRowsCount'?
   for (int i = 0; i < cp.GetRowsCount(); i++) {
                          ^~~~~~~~~~~~
                          getRowsCount
exit status 1
'class CSV_Parser' has no member named 'GetRowsCount'; did you mean 'getRowsCount'?
```